site_name: Capsailer
site_description: CLI tool for delivering Kubernetes applications into air-gapped environments
repo_url: https://github.com/jlnhnng/capsailer
site_url: https://jlnhnng.github.io/capsailer/
theme:
  name: material
  palette:
    primary: blue
    accent: blue
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - User Guide:
      - Installation: user-guide/installation.md
      - Creating Manifests: user-guide/creating-manifests.md
      - Building Bundles: user-guide/building-bundles.md
      - Air-Gapped Deployment: user-guide/air-gapped-deployment.md
  - Command Reference:
      - Overview: commands/overview.md
      - init: commands/init.md
      - build: commands/build.md
      - registry: commands/registry.md
      - push: commands/push.md
      - unpack: commands/unpack.md
  - Examples: examples.md
  - Contributing: contributing.md 