site_name: Documentation
site_description: Documentation for capsailer, CLI tool for delivering Kubernetes applications into air-gapped environments
repo_name: capsailer-cli
repo_url: https://github.com/capsailer/capsailer-cli
site_url: https://capsailer.github.io/capsailer-cli/
copyright: Copyright &copy; 2025 capsailer
theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/favicon.ico
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - content.code.copy

extra:
  generator: false

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - User Guide:
      - Installation: user-guide/installation.md
      - Creating Manifests: user-guide/creating-manifests.md
      - Building Bundles: user-guide/building-bundles.md
      - Air-Gapped Deployment: user-guide/air-gapped-deployment.md
  - Command Reference:
      - Overview: commands/overview.md
      - init: commands/init.md
      - build: commands/build.md
      - registry: commands/registry.md
      - push: commands/push.md
      - unpack: commands/unpack.md
  - Examples: examples.md
  - Contributing: contributing.md 