name: Capsailer CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        cache: true

    - name: Install Dependencies
      run: go mod download

    - name: Build
      run: |
        go build -v -o capsailer cmd/capsailer/main.go cmd/capsailer/commands.go
        chmod +x capsailer

    - name: Run Unit Tests
      run: go test -v ./...

  integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        cache: true

    - name: Install Dependencies
      run: go mod download

    - name: Build
      run: |
        go build -v -o capsailer cmd/capsailer/main.go cmd/capsailer/commands.go
        chmod +x capsailer

    - name: Set up KinD cluster
      uses: helm/kind-action@v1.8.0
      with:
        cluster_name: "kind"
        version: "v0.20.0"

    - name: Create Test Manifest
      run: |
        cat > manifest.yaml << EOF
        images:
          - alpine:3.19.0
          - nginx:1.25.0
        charts:
          - name: nginx
            repo: https://charts.bitnami.com/bitnami
            version: 15.1.4
        EOF

    - name: Test Init Command
      run: |
        ./capsailer init --manifest manifest.yaml
        echo "Init command successful"

    - name: Test Build Command
      run: |
        ./capsailer build --manifest manifest.yaml --output capsailer-bundle.tar.gz
        echo "Build command successful"
        ls -la capsailer-bundle.tar.gz

    - name: Test Registry Deployment
      run: |
        ./capsailer registry --namespace capsailer-test
        echo "Registry deployment successful"
        kubectl get pods -n capsailer-test

    - name: Test Push Command
      run: |
        ./capsailer push --bundle capsailer-bundle.tar.gz --namespace capsailer-test
        echo "Push command successful"
        
        # Verify images in registry
        kubectl port-forward -n capsailer-test svc/registry 5000:5000 &
        sleep 5
        curl -s http://localhost:5000/v2/_catalog | tee catalog.json
        curl -s http://localhost:5000/v2/nginx/tags/list | tee tags.json
        
        # Verify charts in repository
        kubectl port-forward -n capsailer-test svc/chartmuseum 8080:8080 &
        sleep 5
        curl -s http://localhost:8080/api/charts | tee charts.json
        
        # Kill port forwards
        pkill -f "kubectl port-forward"

    - name: Test Deploy Command
      run: |
        # Create a simple values file
        echo "replicaCount: 1" > values.yaml
        
        # Deploy the chart
        ./capsailer deploy --chart nginx --values values.yaml
        
        # Verify deployment
        kubectl get pods
        echo "Deploy command successful"

  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        cache: true

    - name: Install golangci-lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2
        golangci-lint --version

    - name: Run golangci-lint
      run: golangci-lint run ./... 